### ISSUE TITLE
How to change "Alternative Logins" checkmark to Patreon logo?

### ISSUE THREAD

**Issue by merpdotcom** [julianlam/nodebb-plugin-sso-patreon#1]
Greetings. I found where to change the "Alternative Logins" text to "Login with Patreon" in the <nodebb-instance>/public/language/en-US (or en-GB, or de).
And I found in the nodebb-plugins-sso/patreon/library.js where the checkmark is defined with "fa-check" here:
 var constants = Object.freeze({
                'name': 'Patreon',
                'admin': {
                        'route': '/plugins/sso-patreon',
                        'icon': 'fa-check'
                }
        });

How do I tell it to instead of the checkmark to use the Patreon logo, for example patreon.jpg ? What should I change that syntax to, and where should I place the patreon.jpg file?
Thanks for guidance!

**Comment by julianlam** [comment]
Hey there -- currently there's no icon for Patreon [in this list of icons that we use](http://fontawesome.io/icons/). For your use case you'll probably want to use client-side JS to detect the element and change the `<i>` element to `<img />` with the patreon logo or whatnot.
